<?php

namespace ContainerJhOfqvj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTripTypeService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Form\TripType' shared autowired service.
     *
     * @return \App\Form\TripType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\TripType'] = new \App\Form\TripType();
    }
}
