<?php

namespace ContainerJhOfqvj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTripControllerService extends App_KernelDevContainer
{
    /*
     * Gets the public 'App\Controller\TripController' shared autowired service.
     *
     * @return \App\Controller\TripController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\TripController'] = $instance = new \App\Controller\TripController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\TripController', $container));

        return $instance;
    }
}
