<?php

namespace ContainerXxsWeKn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_Dbal_MyDatabaseConnectionService extends App_KernelProdContainer
{
    /*
     * Gets the public 'doctrine.dbal.my_database_connection' shared service.
     *
     * @return \Doctrine\DBAL\Connection
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['doctrine.dbal.my_database_connection'] = ($container->privates['doctrine.dbal.connection_factory'] ?? ($container->privates['doctrine.dbal.connection_factory'] = new \Doctrine\Bundle\DoctrineBundle\ConnectionFactory([])))->createConnection(['driver' => 'pdo_pgsql', 'port' => 5432, 'dbname' => 'communautevoyage', 'user' => 'symfony', 'password' => 123, 'charset' => 'UTF8', 'host' => 'localhost', 'driverOptions' => [], 'defaultTableOptions' => []], new \Doctrine\DBAL\Configuration(), new \Symfony\Bridge\Doctrine\ContainerAwareEventManager(($container->privates['.service_locator.QXcJQkF'] ?? $container->load('get_ServiceLocator_QXcJQkFService')), [0 => 'doctrine.orm.listeners.doctrine_dbal_cache_adapter_schema_subscriber', 1 => 'doctrine.orm.listeners.doctrine_token_provider_schema_subscriber', 2 => [0 => [0 => 'loadClassMetadata'], 1 => 'doctrine.orm.default_listeners.attach_entity_listeners']]), []);
    }
}
