<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGh3SqwZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGh3SqwZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGh3SqwZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGh3SqwZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGh3SqwZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'Gh3SqwZ',
    'container.build_id' => '6ef135a1',
    'container.build_time' => 1647424227,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGh3SqwZ');
