<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJhOfqvj\App_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJhOfqvj/App_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerJhOfqvj.legacy');

    return;
}

if (!\class_exists(App_KernelDevContainer::class, false)) {
    \class_alias(\ContainerJhOfqvj\App_KernelDevContainer::class, App_KernelDevContainer::class, false);
}

return new \ContainerJhOfqvj\App_KernelDevContainer([
    'container.build_hash' => 'JhOfqvj',
    'container.build_id' => 'd8cb5afa',
    'container.build_time' => 1647823251,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJhOfqvj');
