<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEnqd8kC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEnqd8kC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEnqd8kC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEnqd8kC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEnqd8kC\App_KernelDevDebugContainer([
    'container.build_hash' => 'Enqd8kC',
    'container.build_id' => 'f1a9aa97',
    'container.build_time' => 1648456799,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEnqd8kC');
