<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'about' => [[], ['_controller' => 'App\\Controller\\AboutController::index'], [], [['text', '/about']], [], [], []],
    'contact' => [[], ['_controller' => 'App\\Controller\\ContactController::contact'], [], [['text', '/contact']], [], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\CrudTripController::index'], [], [['text', '/crud/trip/']], [], [], []],
    'new' => [[], ['_controller' => 'App\\Controller\\CrudTripController::new'], [], [['text', '/crud/trip/new']], [], [], []],
    'show' => [['id'], ['_controller' => 'App\\Controller\\CrudTripController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/crud/trip']], [], [], []],
    'edit' => [['id'], ['_controller' => 'App\\Controller\\CrudTripController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/crud/trip']], [], [], []],
    'delete' => [['id'], ['_controller' => 'App\\Controller\\CrudTripController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/crud/trip']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/home']], [], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\LoginFormController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\LoginFormController::logout'], [], [['text', '/logout']], [], [], []],
    'register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'trip' => [[], ['_controller' => 'App\\Controller\\TripController::create'], [], [['text', '/trip']], [], [], []],
    'search' => [[], ['_controller' => 'App\\Controller\\TripSearchController::searchCar'], [], [['text', '/trip/search']], [], [], []],
];
