<?php

namespace ContainerEnqd8kC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTripSearchTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\TripSearchType' shared autowired service.
     *
     * @return \App\Form\TripSearchType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/TripSearchType.php';

        return $container->privates['App\\Form\\TripSearchType'] = new \App\Form\TripSearchType();
    }
}
