<?php

namespace ContainerCVppPba;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_RirNAzhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.rirNAzh' shared service.
     *
     * @return \App\Controller\UserAuthenticatorInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\RegistrationController::register()": the $userAuthenticator argument is type-hinted with the non-existent class or interface: "App\\Controller\\UserAuthenticatorInterface". Did you forget to add a use statement?');
    }
}
