<?php

namespace ContainerCVppPba;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTripService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.YQY7QL9.App\Entity\Trip' shared service.
     *
     * @return \App\Entity\Trip
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.YQY7QL9": it references class "App\\Entity\\Trip" but no such service exists.');
    }
}
