controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

homepage:
    path: /
    controller: App\Controller\HomeController::index