<?php

namespace ContainerGwxpUUG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7VtPMIdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7VtPMId' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7VtPMId'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'fileUploader' => ['privates', 'App\\Service\\FileUploader', NULL, 'Cannot autowire service "App\\Service\\FileUploader": argument "$targetDirectory" of method "__construct()" has no type-hint, you should configure its value explicitly.'],
        ], [
            'entityManager' => '?',
            'fileUploader' => 'App\\Service\\FileUploader',
        ]);
    }
}
