<?php

namespace ContainerWMxLHq2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFileUploaderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\FileUploader' shared autowired service.
     *
     * @return \App\Service\FileUploader
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service "App\\Service\\FileUploader": argument "$targetDirectory" of method "__construct()" has no type-hint, you should configure its value explicitly.');
    }
}
