<?php

namespace ContainerQ89e0XV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_5Yl9GPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.5_yl9GP' shared service.
     *
     * @return \App\Controller\AuthenticationUtils
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\AuthenticationController::login()": the $authenticationUtils argument is type-hinted with the non-existent class or interface: "App\\Controller\\AuthenticationUtils". Did you forget to add a use statement?');
    }
}
