<?php

namespace ContainerLSCkY9g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCrudTripControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CrudTripController' shared autowired service.
     *
     * @return \App\Controller\CrudTripController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/CrudTripController.php';

        $container->services['App\\Controller\\CrudTripController'] = $instance = new \App\Controller\CrudTripController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\CrudTripController', $container));

        return $instance;
    }
}
