<?php

namespace ContainerOnqI5PN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginFormControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\LoginFormController' shared autowired service.
     *
     * @return \App\Controller\LoginFormController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/LoginFormController.php';

        $container->services['App\\Controller\\LoginFormController'] = $instance = new \App\Controller\LoginFormController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\LoginFormController', $container));

        return $instance;
    }
}
