<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxsWeKn\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxsWeKn/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerXxsWeKn.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerXxsWeKn\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerXxsWeKn\App_KernelProdContainer([
    'container.build_hash' => 'XxsWeKn',
    'container.build_id' => '860ef1f5',
    'container.build_time' => 1645268466,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxsWeKn');
