<?php

namespace Container3b1jBhc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PJlD2NyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pJlD2Ny' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pJlD2Ny'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'trip' => ['privates', '.errored..service_locator.pJlD2Ny.App\\Entity\\Trip', NULL, 'Cannot autowire service ".service_locator.pJlD2Ny": it references class "App\\Entity\\Trip" but no such service exists.'],
            'tripRepository' => ['privates', 'App\\Repository\\TripRepository', 'getTripRepositoryService', true],
        ], [
            'trip' => 'App\\Entity\\Trip',
            'tripRepository' => 'App\\Repository\\TripRepository',
        ]);
    }
}
