<?php

namespace Container17SR55p;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F6gEVK4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.F6gEVK4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.F6gEVK4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'passwordEncoder' => ['privates', '.errored.DSUPdKb', NULL, 'Cannot determine controller argument for "App\\Controller\\RegistrationController::register()": the $passwordEncoder argument is type-hinted with the non-existent class or interface: "App\\Controller\\UserPasswordEncoderInterface". Did you forget to add a use statement?'],
        ], [
            'entityManager' => '?',
            'passwordEncoder' => '?',
        ]);
    }
}
