<?php

namespace ContainerNxU988Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactNotificationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Notification\ContactNotification' shared autowired service.
     *
     * @return \App\Notification\ContactNotification
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Notification/ContactNotification.php';

        return $container->privates['App\\Notification\\ContactNotification'] = new \App\Notification\ContactNotification(($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService')), ($container->privates['twig'] ?? $container->load('getTwigService')));
    }
}
