<?php

namespace ContainerIW3bN8Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JrLxc7IService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jrLxc7I' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jrLxc7I'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'notification' => ['privates', 'App\\Notification\\ContactNotification', 'getContactNotificationService', true],
        ], [
            'mailer' => '?',
            'notification' => 'App\\Notification\\ContactNotification',
        ]);
    }
}
