<?php

namespace ContainerBUekyF9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_427klOTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.427klOT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.427klOT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'fileUploader' => ['privates', '.errored.Hv2tw3o', NULL, 'Cannot determine controller argument for "App\\Controller\\TripController::create()": the $fileUploader argument is type-hinted with the non-existent class or interface: "App\\Controller\\FileUploader". Did you forget to add a use statement?'],
        ], [
            'entityManager' => '?',
            'fileUploader' => '?',
        ]);
    }
}
