<?php

namespace ContainerBUekyF9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_Hv2tw3oService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.Hv2tw3o' shared service.
     *
     * @return \App\Controller\FileUploader
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\TripController::create()": the $fileUploader argument is type-hinted with the non-existent class or interface: "App\\Controller\\FileUploader". Did you forget to add a use statement?');
    }
}
