vich_uploader:
    db_driver: orm

    mappings:
        image:
            uri_prefix: /upload/images 
            upload_destination: '%kernel.project_dir%/public/upload/images'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
