<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFoYRkWv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFoYRkWv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFoYRkWv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFoYRkWv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFoYRkWv\App_KernelDevDebugContainer([
    'container.build_hash' => 'FoYRkWv',
    'container.build_id' => '14efc3aa',
    'container.build_time' => 1643562890,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFoYRkWv');
